### ISSUE TITLE
实时通道建立成功后登录账号的问题

### ISSUE THREAD

**Issue by jiangbeth** [nezhahq/nezhahq.github.io#21]
不管是GitHub还是极狐登录后都提示
. 访问受限
错误信息：Post "https://github.com/oauth/token": dial tcp: lookup github.com: Temporary failure in name resolution
. 访问受限
错误信息：Post "https://jihulab.com/oauth/token": dial tcp: lookup jihulab.com: Temporary failure in name resolution

**Comment by mingyuetian** [comment]
+1
